# Generated by Django 5.0.4 on 2024-04-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_discipline_abbrev_alter_discipline_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='abbrev',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
