# Generated by Django 5.0.4 on 2024-04-15 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_discipline_abbrev'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='abbrev',
            field=models.CharField(max_length=100),
        ),
    ]
