# Generated by Django 5.0.4 on 2024-04-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_lesson_visit_discipline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson_visit',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
