# Generated by Django 5.0.4 on 2024-04-17 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_lesson_visit_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson_visit',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.discipline'),
        ),
        migrations.AlterField(
            model_name='lesson_visit',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.student'),
        ),
    ]
