# Generated by Django 5.0.4 on 2024-04-17 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_lesson_visit_discipline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson_visit',
            name='discipline',
            field=models.CharField(max_length=100),
        ),
    ]
