# Generated by Django 5.0.4 on 2024-04-17 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_lesson_visit_groups_alter_discipline_year_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson_visit',
            old_name='groups',
            new_name='group',
        ),
    ]
